name: 自动部署 fditor-ui
on:
  create:
    tags: # 只在创建标签时触发
      - 'v*' # 匹配v开头的标签（如v1.0.0）
jobs:
  deploy:
    runs-on: ubuntu-latest # 使用GitHub提供的Ubuntu环境
    steps:
      - name: 部署到服务器
        uses: appleboy/ssh-action@master # 使用SSH工具连接服务器
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # 服务器上执行的部署命令
          script: |
            # 拉取最新镜像（若使用Docker Hub）
            docker pull ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}

            # 停止并删除旧容器
            if [ $(docker ps -q -f name=${{ secrets.DOCKER_IMAGE_NAME }}) ]; then
              docker stop ${{ secrets.DOCKER_IMAGE_NAME }}
              docker rm ${{ secrets.DOCKER_IMAGE_NAME }}
            fi

            # 启动新容器
            docker run -d \
              --name ${{ secrets.DOCKER_IMAGE_NAME }} \
              -p 80:80 \
              --restart always \
              ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}

            # 清理无用镜像
            docker image prune -f
